// Package issue1168 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue1168

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// Detail A human readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty" xml:"detail"`

	// Instance An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty" xml:"instance"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty" xml:"status"`

	// Title A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable
	Title *string `json:"title,omitempty" xml:"title"`

	// Type An absolute URI that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).
	Type                 *string                `json:"type,omitempty" xml:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Misc400Error defines model for Misc400Error.
type Misc400Error = ProblemDetails

// Misc404Error defines model for Misc404Error.
type Misc404Error = ProblemDetails

type RawMessage []byte

// MarshalJSON returns the raw bytes as JSON.
func (r RawMessage) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	return r, nil
}

// UnmarshalJSON sets the raw bytes from JSON input.
func (r *RawMessage) UnmarshalJSON(data []byte) error {
	*r = append((*r)[0:0], data...)
	return nil
}

// MarshalXML encodes the raw XML message into the encoder, re-wrapping
// it within the provided start element.
func (r RawMessage) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(r) == 0 {
		return nil
	}

	d := xml.NewDecoder(bytes.NewReader(r))
	// Skip the original start element from the stored raw XML
	_, err := d.Token()
	if err != nil {
		return err
	}

	// Write the caller-provided start element
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	// Copy all inner tokens until we reach the matching end element
	depth := 1
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
			if depth == 0 {
				return e.EncodeToken(start.End())
			}
		}
		if err := e.EncodeToken(xml.CopyToken(tok)); err != nil {
			return err
		}
	}
}

// UnmarshalXML captures a full XML element (including children) into raw bytes.
func (r *RawMessage) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	data, err := CaptureXMLElement(d, start)
	if err != nil {
		return err
	}
	*r = data
	return nil
}

// CaptureXMLElement reads an entire XML element from the decoder and returns it as bytes.
func CaptureXMLElement(d *xml.Decoder, start xml.StartElement) ([]byte, error) {
	buf := new(bytes.Buffer)
	encoder := xml.NewEncoder(buf)

	if err := encoder.EncodeToken(start); err != nil {
		return nil, err
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return nil, err
		}

		if err = encoder.EncodeToken(tok); err != nil {
			return nil, err
		}

		if end, ok := tok.(xml.EndElement); ok && end.Name == start.Name {
			encoder.Flush()
			break
		}
	}

	return buf.Bytes(), nil
}

// Getter for additional properties for ProblemDetails. Returns the specified
// element and whether it was found
func (a ProblemDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetails
func (a *ProblemDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Override default XML handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	knownFields := map[string]bool{
		"detail":   true,
		"instance": true,
		"status":   true,
		"title":    true,
		"type":     true,
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "detail":
				if err := d.DecodeElement(&a.Detail, &t); err != nil {
					return fmt.Errorf("error reading 'detail': %w", err)
				}
			case "instance":
				if err := d.DecodeElement(&a.Instance, &t); err != nil {
					return fmt.Errorf("error reading 'instance': %w", err)
				}
			case "status":
				if err := d.DecodeElement(&a.Status, &t); err != nil {
					return fmt.Errorf("error reading 'status': %w", err)
				}
			case "title":
				if err := d.DecodeElement(&a.Title, &t); err != nil {
					return fmt.Errorf("error reading 'title': %w", err)
				}
			case "type":
				if err := d.DecodeElement(&a.Type, &t); err != nil {
					return fmt.Errorf("error reading 'type': %w", err)
				}
			default:
				if !knownFields[t.Name.Local] {
					if a.AdditionalProperties == nil {
						a.AdditionalProperties = make(map[string]interface{})
					}
					var val interface{}
					if err := d.DecodeElement(&val, &t); err != nil {
						return fmt.Errorf("error unmarshaling field %s: %w", t.Name.Local, err)
					}
					a.AdditionalProperties[t.Name.Local] = val
				} else {
					if err := d.Skip(); err != nil {
						return err
					}
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// Override default XML handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if a.Detail != nil {
		if err := e.EncodeElement(a.Detail, xml.StartElement{Name: xml.Name{Local: "detail"}}); err != nil {
			return fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		if err := e.EncodeElement(a.Instance, xml.StartElement{Name: xml.Name{Local: "instance"}}); err != nil {
			return fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		if err := e.EncodeElement(a.Status, xml.StartElement{Name: xml.Name{Local: "status"}}); err != nil {
			return fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		if err := e.EncodeElement(a.Title, xml.StartElement{Name: xml.Name{Local: "title"}}); err != nil {
			return fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		if err := e.EncodeElement(a.Type, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
			return fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		if err := e.EncodeElement(field, xml.StartElement{Name: xml.Name{Local: fieldName}}); err != nil {
			return fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return e.EncodeToken(start.End())
}
