// Package issue52 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue52

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// Person defines model for Person.
type Person struct {
	Age                  *float32               `json:"age,omitempty" xml:"age"`
	Metadata             string                 `json:"metadata" xml:"metadata"`
	Name                 *string                `json:"name,omitempty" xml:"name"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

type RawMessage []byte

// MarshalJSON returns the raw bytes as JSON.
func (r RawMessage) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	return r, nil
}

// UnmarshalJSON sets the raw bytes from JSON input.
func (r *RawMessage) UnmarshalJSON(data []byte) error {
	*r = append((*r)[0:0], data...)
	return nil
}

// MarshalXML encodes the raw XML message into the encoder, re-wrapping
// it within the provided start element.
func (r RawMessage) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(r) == 0 {
		return nil
	}

	d := xml.NewDecoder(bytes.NewReader(r))
	// Skip the original start element from the stored raw XML
	_, err := d.Token()
	if err != nil {
		return err
	}

	// Write the caller-provided start element
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	// Copy all inner tokens until we reach the matching end element
	depth := 1
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
			if depth == 0 {
				return e.EncodeToken(start.End())
			}
		}
		if err := e.EncodeToken(xml.CopyToken(tok)); err != nil {
			return err
		}
	}
}

// UnmarshalXML captures a full XML element (including children) into raw bytes.
func (r *RawMessage) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	data, err := CaptureXMLElement(d, start)
	if err != nil {
		return err
	}
	*r = data
	return nil
}

// CaptureXMLElement reads an entire XML element from the decoder and returns it as bytes.
func CaptureXMLElement(d *xml.Decoder, start xml.StartElement) ([]byte, error) {
	buf := new(bytes.Buffer)
	encoder := xml.NewEncoder(buf)

	if err := encoder.EncodeToken(start); err != nil {
		return nil, err
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return nil, err
		}

		if err = encoder.EncodeToken(tok); err != nil {
			return nil, err
		}

		if end, ok := tok.(xml.EndElement); ok && end.Name == start.Name {
			encoder.Flush()
			break
		}
	}

	return buf.Bytes(), nil
}

// Getter for additional properties for Person. Returns the specified
// element and whether it was found
func (a Person) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Person
func (a *Person) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Person to handle AdditionalProperties
func (a *Person) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["age"]; found {
		err = json.Unmarshal(raw, &a.Age)
		if err != nil {
			return fmt.Errorf("error reading 'age': %w", err)
		}
		delete(object, "age")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Person to handle AdditionalProperties
func (a Person) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Age != nil {
		object["age"], err = json.Marshal(a.Age)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'age': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Override default XML handling for Person to handle AdditionalProperties
func (a *Person) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	knownFields := map[string]bool{
		"age":      true,
		"metadata": true,
		"name":     true,
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "age":
				if err := d.DecodeElement(&a.Age, &t); err != nil {
					return fmt.Errorf("error reading 'age': %w", err)
				}
			case "metadata":
				if err := d.DecodeElement(&a.Metadata, &t); err != nil {
					return fmt.Errorf("error reading 'metadata': %w", err)
				}
			case "name":
				if err := d.DecodeElement(&a.Name, &t); err != nil {
					return fmt.Errorf("error reading 'name': %w", err)
				}
			default:
				if !knownFields[t.Name.Local] {
					if a.AdditionalProperties == nil {
						a.AdditionalProperties = make(map[string]interface{})
					}
					var val interface{}
					if err := d.DecodeElement(&val, &t); err != nil {
						return fmt.Errorf("error unmarshaling field %s: %w", t.Name.Local, err)
					}
					a.AdditionalProperties[t.Name.Local] = val
				} else {
					if err := d.Skip(); err != nil {
						return err
					}
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// Override default XML handling for Person to handle AdditionalProperties
func (a Person) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if a.Age != nil {
		if err := e.EncodeElement(a.Age, xml.StartElement{Name: xml.Name{Local: "age"}}); err != nil {
			return fmt.Errorf("error marshaling 'age': %w", err)
		}
	}

	if err := e.EncodeElement(a.Metadata, xml.StartElement{Name: xml.Name{Local: "metadata"}}); err != nil {
		return fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Name != nil {
		if err := e.EncodeElement(a.Name, xml.StartElement{Name: xml.Name{Local: "name"}}); err != nil {
			return fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		if err := e.EncodeElement(field, xml.StartElement{Name: xml.Name{Local: fieldName}}); err != nil {
			return fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return e.EncodeToken(start.End())
}
