// Package issue1767 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue1767

import (
	"bytes"
	"encoding/xml"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Alarm Alarm Information
type Alarm struct {
	// UnderscoreId Identifier of the Alarm.
	UnderscoreId *openapi_types.UUID `json:"_id,omitempty" xml:"_id"`

	// Id Identifier of the Alarm.
	Id *openapi_types.UUID `json:"id,omitempty" xml:"id"`
}

type RawMessage []byte

// MarshalJSON returns the raw bytes as JSON.
func (r RawMessage) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	return r, nil
}

// UnmarshalJSON sets the raw bytes from JSON input.
func (r *RawMessage) UnmarshalJSON(data []byte) error {
	*r = append((*r)[0:0], data...)
	return nil
}

// MarshalXML encodes the raw XML message into the encoder, re-wrapping
// it within the provided start element.
func (r RawMessage) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(r) == 0 {
		return nil
	}

	d := xml.NewDecoder(bytes.NewReader(r))
	// Skip the original start element from the stored raw XML
	_, err := d.Token()
	if err != nil {
		return err
	}

	// Write the caller-provided start element
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	// Copy all inner tokens until we reach the matching end element
	depth := 1
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
			if depth == 0 {
				return e.EncodeToken(start.End())
			}
		}
		if err := e.EncodeToken(xml.CopyToken(tok)); err != nil {
			return err
		}
	}
}

// UnmarshalXML captures a full XML element (including children) into raw bytes.
func (r *RawMessage) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	data, err := CaptureXMLElement(d, start)
	if err != nil {
		return err
	}
	*r = data
	return nil
}

// CaptureXMLElement reads an entire XML element from the decoder and returns it as bytes.
func CaptureXMLElement(d *xml.Decoder, start xml.StartElement) ([]byte, error) {
	buf := new(bytes.Buffer)
	encoder := xml.NewEncoder(buf)

	if err := encoder.EncodeToken(start); err != nil {
		return nil, err
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return nil, err
		}

		if err = encoder.EncodeToken(tok); err != nil {
			return nil, err
		}

		if end, ok := tok.(xml.EndElement); ok && end.Name == start.Name {
			encoder.Flush()
			break
		}
	}

	return buf.Bytes(), nil
}
