// Package xml_marshal provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package xml_marshal

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AdditionalPropsInt defines model for AdditionalPropsInt.
type AdditionalPropsInt struct {
	Id                   int            `json:"id" xml:"id"`
	Label                *string        `json:"label,omitempty" xml:"label"`
	AdditionalProperties map[string]int `json:"-"`
}

// AdditionalPropsString defines model for AdditionalPropsString.
type AdditionalPropsString struct {
	Name                 string            `json:"name" xml:"name"`
	AdditionalProperties map[string]string `json:"-"`
}

// AnyOfUnion defines model for AnyOfUnion.
type AnyOfUnion struct {
	union  json.RawMessage
	xunion RawMessage
}

// BaseObject defines model for BaseObject.
type BaseObject struct {
	Id int `json:"id" xml:"id"`
}

// BirthDate defines model for BirthDate.
type BirthDate = XMLDate

// DateHolder defines model for DateHolder.
type DateHolder struct {
	AttrDate     *XMLDate   `json:"attr_date,omitempty" xml:"attr_date,attr"`
	DateList     *[]XMLDate `json:"date_list,omitempty" xml:"date_list"`
	OptionalDate *XMLDate   `json:"optional_date,omitempty" xml:"optional_date"`
	RequiredDate XMLDate    `json:"required_date" xml:"required_date"`
	Stamp        time.Time  `json:"stamp" xml:"stamp"`
}

// DateTimeWrapper defines model for DateTimeWrapper.
type DateTimeWrapper struct {
	DateTime time.Time `json:"DateTime" xml:"DateTime"`
}

// DateWrapper defines model for DateWrapper.
type DateWrapper struct {
	Date XMLDate `json:"Date" xml:"Date"`
}

// DiscriminatorVariant1 defines model for DiscriminatorVariant1.
type DiscriminatorVariant1 struct {
	Kind string `json:"kind" xml:"kind"`
	Name string `json:"name" xml:"name"`
}

// DiscriminatorVariant2 defines model for DiscriminatorVariant2.
type DiscriminatorVariant2 struct {
	Count int    `json:"count" xml:"count"`
	Kind  string `json:"kind" xml:"kind"`
}

// ExtendedObject defines model for ExtendedObject.
type ExtendedObject struct {
	Description *string `json:"description,omitempty" xml:"description"`
	Id          int     `json:"id" xml:"id"`
	Name        string  `json:"name" xml:"name"`
}

// InnerObject defines model for InnerObject.
type InnerObject struct {
	Value string `json:"value" xml:"value"`
}

// ObjectWithOptionalFields defines model for ObjectWithOptionalFields.
type ObjectWithOptionalFields struct {
	OptionalInt    *int    `json:"optional_int,omitempty" xml:"optional_int"`
	OptionalString *string `json:"optional_string,omitempty" xml:"optional_string"`
	RequiredField  string  `json:"required_field" xml:"required_field"`
}

// OneOfVariantA defines model for OneOfVariantA.
type OneOfVariantA struct {
	ValueA   *int   `json:"valueA,omitempty" xml:"valueA"`
	VariantA string `json:"variantA" xml:"variantA"`
}

// OneOfVariantB defines model for OneOfVariantB.
type OneOfVariantB struct {
	ValueB   *bool  `json:"valueB,omitempty" xml:"valueB"`
	VariantB string `json:"variantB" xml:"variantB"`
}

// OuterObject defines model for OuterObject.
type OuterObject struct {
	Inner InnerObject `json:"inner" xml:"inner"`
	Label string      `json:"label" xml:"label"`
}

// SimpleObject defines model for SimpleObject.
type SimpleObject struct {
	Email *string `json:"email,omitempty" xml:"email"`
	Id    int     `json:"id" xml:"id"`
	Name  string  `json:"name" xml:"name"`
}

// SimpleUnion defines model for SimpleUnion.
type SimpleUnion struct {
	union  json.RawMessage
	xunion RawMessage
}

// UnionWithAdditionalProps defines model for UnionWithAdditionalProps.
type UnionWithAdditionalProps struct {
	Type                 string            `json:"type" xml:"type"`
	AdditionalProperties map[string]string `json:"-"`
	union                json.RawMessage
	xunion               RawMessage
}

// UnionWithDiscriminator defines model for UnionWithDiscriminator.
type UnionWithDiscriminator struct {
	union  json.RawMessage
	xunion RawMessage
}

// UnionWithFixedProps defines model for UnionWithFixedProps.
type UnionWithFixedProps struct {
	Type   string `json:"type" xml:"type"`
	union  json.RawMessage
	xunion RawMessage
}

// XmlNamedObject defines model for XmlNamedObject.
type XmlNamedObject struct {
	Count *int   `json:"count,omitempty" xml:"obj_count"`
	Title string `json:"title" xml:"obj_title"`
}

type RawMessage []byte

// MarshalJSON returns the raw bytes as JSON.
func (r RawMessage) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	return r, nil
}

// UnmarshalJSON sets the raw bytes from JSON input.
func (r *RawMessage) UnmarshalJSON(data []byte) error {
	*r = append((*r)[0:0], data...)
	return nil
}

// MarshalXML encodes the raw XML message into the encoder, re-wrapping
// it within the provided start element.
func (r RawMessage) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(r) == 0 {
		return nil
	}

	d := xml.NewDecoder(bytes.NewReader(r))
	// Skip the original start element from the stored raw XML
	_, err := d.Token()
	if err != nil {
		return err
	}

	// Write the caller-provided start element
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	// Copy all inner tokens until we reach the matching end element
	depth := 1
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
			if depth == 0 {
				return e.EncodeToken(start.End())
			}
		}
		if err := e.EncodeToken(xml.CopyToken(tok)); err != nil {
			return err
		}
	}
}

// UnmarshalXML captures a full XML element (including children) into raw bytes.
func (r *RawMessage) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	data, err := CaptureXMLElement(d, start)
	if err != nil {
		return err
	}
	*r = data
	return nil
}

// CaptureXMLElement reads an entire XML element from the decoder and returns it as bytes.
func CaptureXMLElement(d *xml.Decoder, start xml.StartElement) ([]byte, error) {
	buf := new(bytes.Buffer)
	encoder := xml.NewEncoder(buf)

	if err := encoder.EncodeToken(start); err != nil {
		return nil, err
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return nil, err
		}

		if err = encoder.EncodeToken(tok); err != nil {
			return nil, err
		}

		if end, ok := tok.(xml.EndElement); ok && end.Name == start.Name {
			encoder.Flush()
			break
		}
	}

	return buf.Bytes(), nil
}

// Getter for additional properties for AdditionalPropsInt. Returns the specified
// element and whether it was found
func (a AdditionalPropsInt) Get(fieldName string) (value int, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AdditionalPropsInt
func (a *AdditionalPropsInt) Set(fieldName string, value int) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]int)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AdditionalPropsInt to handle AdditionalProperties
func (a *AdditionalPropsInt) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["label"]; found {
		err = json.Unmarshal(raw, &a.Label)
		if err != nil {
			return fmt.Errorf("error reading 'label': %w", err)
		}
		delete(object, "label")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]int)
		for fieldName, fieldBuf := range object {
			var fieldVal int
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AdditionalPropsInt to handle AdditionalProperties
func (a AdditionalPropsInt) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.Label != nil {
		object["label"], err = json.Marshal(a.Label)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'label': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Override default XML handling for AdditionalPropsInt to handle AdditionalProperties
func (a *AdditionalPropsInt) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	knownFields := map[string]bool{
		"id":    true,
		"label": true,
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				if err := d.DecodeElement(&a.Id, &t); err != nil {
					return fmt.Errorf("error reading 'id': %w", err)
				}
			case "label":
				if err := d.DecodeElement(&a.Label, &t); err != nil {
					return fmt.Errorf("error reading 'label': %w", err)
				}
			default:
				if !knownFields[t.Name.Local] {
					if a.AdditionalProperties == nil {
						a.AdditionalProperties = make(map[string]int)
					}
					var val int
					if err := d.DecodeElement(&val, &t); err != nil {
						return fmt.Errorf("error unmarshaling field %s: %w", t.Name.Local, err)
					}
					a.AdditionalProperties[t.Name.Local] = val
				} else {
					if err := d.Skip(); err != nil {
						return err
					}
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// Override default XML handling for AdditionalPropsInt to handle AdditionalProperties
func (a AdditionalPropsInt) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := e.EncodeElement(a.Id, xml.StartElement{Name: xml.Name{Local: "id"}}); err != nil {
		return fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.Label != nil {
		if err := e.EncodeElement(a.Label, xml.StartElement{Name: xml.Name{Local: "label"}}); err != nil {
			return fmt.Errorf("error marshaling 'label': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		if err := e.EncodeElement(field, xml.StartElement{Name: xml.Name{Local: fieldName}}); err != nil {
			return fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return e.EncodeToken(start.End())
}

// Getter for additional properties for AdditionalPropsString. Returns the specified
// element and whether it was found
func (a AdditionalPropsString) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AdditionalPropsString
func (a *AdditionalPropsString) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AdditionalPropsString to handle AdditionalProperties
func (a *AdditionalPropsString) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AdditionalPropsString to handle AdditionalProperties
func (a AdditionalPropsString) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Override default XML handling for AdditionalPropsString to handle AdditionalProperties
func (a *AdditionalPropsString) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	knownFields := map[string]bool{
		"name": true,
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "name":
				if err := d.DecodeElement(&a.Name, &t); err != nil {
					return fmt.Errorf("error reading 'name': %w", err)
				}
			default:
				if !knownFields[t.Name.Local] {
					if a.AdditionalProperties == nil {
						a.AdditionalProperties = make(map[string]string)
					}
					var val string
					if err := d.DecodeElement(&val, &t); err != nil {
						return fmt.Errorf("error unmarshaling field %s: %w", t.Name.Local, err)
					}
					a.AdditionalProperties[t.Name.Local] = val
				} else {
					if err := d.Skip(); err != nil {
						return err
					}
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// Override default XML handling for AdditionalPropsString to handle AdditionalProperties
func (a AdditionalPropsString) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := e.EncodeElement(a.Name, xml.StartElement{Name: xml.Name{Local: "name"}}); err != nil {
		return fmt.Errorf("error marshaling 'name': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		if err := e.EncodeElement(field, xml.StartElement{Name: xml.Name{Local: fieldName}}); err != nil {
			return fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return e.EncodeToken(start.End())
}

// Getter for additional properties for UnionWithAdditionalProps. Returns the specified
// element and whether it was found
func (a UnionWithAdditionalProps) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UnionWithAdditionalProps
func (a *UnionWithAdditionalProps) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// AsOneOfVariantA returns the union data inside the AnyOfUnion as a OneOfVariantA
func (t AnyOfUnion) AsOneOfVariantA() (OneOfVariantA, error) {
	var body OneOfVariantA
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantA overwrites any union data inside the AnyOfUnion as the provided OneOfVariantA
func (t *AnyOfUnion) FromOneOfVariantA(v OneOfVariantA) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantA performs a merge with any union data inside the AnyOfUnion, using the provided OneOfVariantA
func (t *AnyOfUnion) MergeOneOfVariantA(v OneOfVariantA) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

// AsOneOfVariantB returns the union data inside the AnyOfUnion as a OneOfVariantB
func (t AnyOfUnion) AsOneOfVariantB() (OneOfVariantB, error) {
	var body OneOfVariantB
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantB overwrites any union data inside the AnyOfUnion as the provided OneOfVariantB
func (t *AnyOfUnion) FromOneOfVariantB(v OneOfVariantB) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantB performs a merge with any union data inside the AnyOfUnion, using the provided OneOfVariantB
func (t *AnyOfUnion) MergeOneOfVariantB(v OneOfVariantB) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

func (t AnyOfUnion) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnyOfUnion) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

func (t AnyOfUnion) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(t.xunion) > 0 {
		return t.xunion.MarshalXML(e, start)
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}
	return e.EncodeToken(start.End())
}

func (t *AnyOfUnion) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var err error

	t.xunion, err = CaptureXMLElement(d, start)
	if err != nil {
		return err
	}

	return nil
}

// AsOneOfVariantA returns the union data inside the SimpleUnion as a OneOfVariantA
func (t SimpleUnion) AsOneOfVariantA() (OneOfVariantA, error) {
	var body OneOfVariantA
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantA overwrites any union data inside the SimpleUnion as the provided OneOfVariantA
func (t *SimpleUnion) FromOneOfVariantA(v OneOfVariantA) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantA performs a merge with any union data inside the SimpleUnion, using the provided OneOfVariantA
func (t *SimpleUnion) MergeOneOfVariantA(v OneOfVariantA) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

// AsOneOfVariantB returns the union data inside the SimpleUnion as a OneOfVariantB
func (t SimpleUnion) AsOneOfVariantB() (OneOfVariantB, error) {
	var body OneOfVariantB
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantB overwrites any union data inside the SimpleUnion as the provided OneOfVariantB
func (t *SimpleUnion) FromOneOfVariantB(v OneOfVariantB) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantB performs a merge with any union data inside the SimpleUnion, using the provided OneOfVariantB
func (t *SimpleUnion) MergeOneOfVariantB(v OneOfVariantB) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

func (t SimpleUnion) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SimpleUnion) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

func (t SimpleUnion) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(t.xunion) > 0 {
		return t.xunion.MarshalXML(e, start)
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}
	return e.EncodeToken(start.End())
}

func (t *SimpleUnion) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var err error

	t.xunion, err = CaptureXMLElement(d, start)
	if err != nil {
		return err
	}

	return nil
}

// AsOneOfVariantA returns the union data inside the UnionWithAdditionalProps as a OneOfVariantA
func (t UnionWithAdditionalProps) AsOneOfVariantA() (OneOfVariantA, error) {
	var body OneOfVariantA
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantA overwrites any union data inside the UnionWithAdditionalProps as the provided OneOfVariantA
func (t *UnionWithAdditionalProps) FromOneOfVariantA(v OneOfVariantA) error {
	t.Type = "a"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantA performs a merge with any union data inside the UnionWithAdditionalProps, using the provided OneOfVariantA
func (t *UnionWithAdditionalProps) MergeOneOfVariantA(v OneOfVariantA) error {
	t.Type = "a"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

// AsOneOfVariantB returns the union data inside the UnionWithAdditionalProps as a OneOfVariantB
func (t UnionWithAdditionalProps) AsOneOfVariantB() (OneOfVariantB, error) {
	var body OneOfVariantB
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantB overwrites any union data inside the UnionWithAdditionalProps as the provided OneOfVariantB
func (t *UnionWithAdditionalProps) FromOneOfVariantB(v OneOfVariantB) error {
	t.Type = "b"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantB performs a merge with any union data inside the UnionWithAdditionalProps, using the provided OneOfVariantB
func (t *UnionWithAdditionalProps) MergeOneOfVariantB(v OneOfVariantB) error {
	t.Type = "b"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

func (t UnionWithAdditionalProps) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type" xml:"type"`
	}
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &discriminator)
		if err != nil {
			return "", err
		}
		return discriminator.Discriminator, nil
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &discriminator)
		if err != nil {
			return "", err
		}
		return discriminator.Discriminator, nil
	}
	return "", nil
}

func (t UnionWithAdditionalProps) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "a":
		return t.AsOneOfVariantA()
	case "b":
		return t.AsOneOfVariantB()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

// AsDiscriminatorVariant1 returns the union data inside the UnionWithDiscriminator as a DiscriminatorVariant1
func (t UnionWithDiscriminator) AsDiscriminatorVariant1() (DiscriminatorVariant1, error) {
	var body DiscriminatorVariant1
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromDiscriminatorVariant1 overwrites any union data inside the UnionWithDiscriminator as the provided DiscriminatorVariant1
func (t *UnionWithDiscriminator) FromDiscriminatorVariant1(v DiscriminatorVariant1) error {
	v.Kind = "variant1"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeDiscriminatorVariant1 performs a merge with any union data inside the UnionWithDiscriminator, using the provided DiscriminatorVariant1
func (t *UnionWithDiscriminator) MergeDiscriminatorVariant1(v DiscriminatorVariant1) error {
	v.Kind = "variant1"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

// AsDiscriminatorVariant2 returns the union data inside the UnionWithDiscriminator as a DiscriminatorVariant2
func (t UnionWithDiscriminator) AsDiscriminatorVariant2() (DiscriminatorVariant2, error) {
	var body DiscriminatorVariant2
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromDiscriminatorVariant2 overwrites any union data inside the UnionWithDiscriminator as the provided DiscriminatorVariant2
func (t *UnionWithDiscriminator) FromDiscriminatorVariant2(v DiscriminatorVariant2) error {
	v.Kind = "variant2"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeDiscriminatorVariant2 performs a merge with any union data inside the UnionWithDiscriminator, using the provided DiscriminatorVariant2
func (t *UnionWithDiscriminator) MergeDiscriminatorVariant2(v DiscriminatorVariant2) error {
	v.Kind = "variant2"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

func (t UnionWithDiscriminator) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind" xml:"kind"`
	}
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &discriminator)
		if err != nil {
			return "", err
		}
		return discriminator.Discriminator, nil
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &discriminator)
		if err != nil {
			return "", err
		}
		return discriminator.Discriminator, nil
	}
	return "", nil
}

func (t UnionWithDiscriminator) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "variant1":
		return t.AsDiscriminatorVariant1()
	case "variant2":
		return t.AsDiscriminatorVariant2()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UnionWithDiscriminator) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UnionWithDiscriminator) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

func (t UnionWithDiscriminator) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(t.xunion) > 0 {
		return t.xunion.MarshalXML(e, start)
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}
	return e.EncodeToken(start.End())
}

func (t *UnionWithDiscriminator) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var err error

	t.xunion, err = CaptureXMLElement(d, start)
	if err != nil {
		return err
	}

	return nil
}

// AsOneOfVariantA returns the union data inside the UnionWithFixedProps as a OneOfVariantA
func (t UnionWithFixedProps) AsOneOfVariantA() (OneOfVariantA, error) {
	var body OneOfVariantA
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantA overwrites any union data inside the UnionWithFixedProps as the provided OneOfVariantA
func (t *UnionWithFixedProps) FromOneOfVariantA(v OneOfVariantA) error {
	t.Type = "a"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantA performs a merge with any union data inside the UnionWithFixedProps, using the provided OneOfVariantA
func (t *UnionWithFixedProps) MergeOneOfVariantA(v OneOfVariantA) error {
	t.Type = "a"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

// AsOneOfVariantB returns the union data inside the UnionWithFixedProps as a OneOfVariantB
func (t UnionWithFixedProps) AsOneOfVariantB() (OneOfVariantB, error) {
	var body OneOfVariantB
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &body)
		if err != nil {
			return body, err
		}
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &body)
		if err != nil {
			return body, err
		}
	}
	return body, nil
}

// FromOneOfVariantB overwrites any union data inside the UnionWithFixedProps as the provided OneOfVariantB
func (t *UnionWithFixedProps) FromOneOfVariantB(v OneOfVariantB) error {
	t.Type = "b"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	t.union = b
	b, err = xml.Marshal(v)
	if err != nil {
		return err
	}
	t.xunion = b

	return nil
}

// MergeOneOfVariantB performs a merge with any union data inside the UnionWithFixedProps, using the provided OneOfVariantB
func (t *UnionWithFixedProps) MergeOneOfVariantB(v OneOfVariantB) error {
	t.Type = "b"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(b, t.union)
	t.union = merged

	// For XML, re-marshal the merged result
	bx, errx := xml.Marshal(v)
	if errx != nil {
		return errx
	}
	t.xunion = bx

	return err
}

func (t UnionWithFixedProps) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type" xml:"type"`
	}
	if len(t.union) > 0 {
		err := json.Unmarshal(t.union, &discriminator)
		if err != nil {
			return "", err
		}
		return discriminator.Discriminator, nil
	}
	if len(t.xunion) > 0 {
		err := xml.Unmarshal(t.xunion, &discriminator)
		if err != nil {
			return "", err
		}
		return discriminator.Discriminator, nil
	}
	return "", nil
}

func (t UnionWithFixedProps) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "a":
		return t.AsOneOfVariantA()
	case "b":
		return t.AsOneOfVariantB()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UnionWithFixedProps) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *UnionWithFixedProps) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	return err
}

func (t UnionWithFixedProps) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	// Marshal with fixed properties merged into the union content
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	// Write union inner content first
	if len(t.xunion) > 0 {
		d := xml.NewDecoder(bytes.NewReader([]byte(t.xunion)))
		// Skip the original start element
		if _, err := d.Token(); err != nil {
			return err
		}
		depth := 1
		for depth > 0 {
			tok, err := d.Token()
			if err != nil {
				return err
			}
			switch tok.(type) {
			case xml.StartElement:
				depth++
			case xml.EndElement:
				depth--
			}
			if depth > 0 {
				if err := e.EncodeToken(xml.CopyToken(tok)); err != nil {
					return err
				}
			}
		}
	}

	// Write fixed properties (ensures they are present even if not in xunion)

	if err := e.EncodeElement(t.Type, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
		return fmt.Errorf("error marshaling 'type': %w", err)
	}

	return e.EncodeToken(start.End())
}

func (t *UnionWithFixedProps) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var err error

	t.xunion, err = CaptureXMLElement(d, start)
	if err != nil {
		return err
	}

	// Extract fixed properties from the captured XML
	type xmlProps struct {
		Type string `xml:"type"`
	}
	var props xmlProps
	if err := xml.Unmarshal(t.xunion, &props); err != nil {
		return err
	}
	t.Type = props.Type
	return nil
}

// Override default JSON handling for UnionWithAdditionalProps to handle AdditionalProperties and union
func (a *UnionWithAdditionalProps) UnmarshalJSON(b []byte) error {
	err := a.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default XML handling for UnionWithAdditionalProps to handle AdditionalProperties and union
func (a *UnionWithAdditionalProps) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	// Capture the full XML element for the union
	raw, err := CaptureXMLElement(d, start)
	if err != nil {
		return err
	}
	a.xunion = raw

	// Now parse the captured XML to extract properties and additional properties
	knownFields := map[string]bool{
		"type": true,
	}

	innerDecoder := xml.NewDecoder(bytes.NewReader(raw))
	// Skip the start element
	if _, err := innerDecoder.Token(); err != nil {
		return err
	}

	for {
		tok, err := innerDecoder.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "type":
				if err := innerDecoder.DecodeElement(&a.Type, &t); err != nil {
					return fmt.Errorf("error reading 'type': %w", err)
				}
			default:
				if !knownFields[t.Name.Local] {
					if a.AdditionalProperties == nil {
						a.AdditionalProperties = make(map[string]string)
					}
					var val string
					if err := innerDecoder.DecodeElement(&val, &t); err != nil {
						return fmt.Errorf("error unmarshaling field %s: %w", t.Name.Local, err)
					}
					a.AdditionalProperties[t.Name.Local] = val
				} else {
					if err := innerDecoder.Skip(); err != nil {
						return err
					}
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// Override default JSON handling for UnionWithAdditionalProps to handle AdditionalProperties and union
func (a UnionWithAdditionalProps) MarshalJSON() ([]byte, error) {
	var err error
	b, err := a.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if a.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Override default XML handling for UnionWithAdditionalProps to handle AdditionalProperties and union
func (a UnionWithAdditionalProps) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(a.xunion) > 0 {
		return a.xunion.MarshalXML(e, start)
	}

	// No union data; marshal properties and additional properties
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := e.EncodeElement(a.Type, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
		return fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		if err := e.EncodeElement(field, xml.StartElement{Name: xml.Name{Local: fieldName}}); err != nil {
			return fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return e.EncodeToken(start.End())
}

// XMLDate is the Go type for OpenAPI `format: date` values. It renders as a
// plain CCYY-MM-DD date in both JSON and XML, including when used as an XML
// attribute.
//
// It deliberately has the same underlying type as
// github.com/oapi-codegen/runtime/types.Date (a struct embedding time.Time)
// rather than embedding that type, so it stays convertible to it. The runtime's
// parameter binding detects dates with reflect ConvertibleTo checks against
// types.Date; a type that merely embedded types.Date would fail those checks
// and silently bind the zero date in deepObject parameters.
type XMLDate struct {
	time.Time
}

// MarshalText renders the date as CCYY-MM-DD.
//
// This is the method types.Date is missing. Without it, encoding/xml finds the
// MarshalText promoted from the embedded time.Time and emits a full RFC3339
// timestamp, which is invalid for an xsd:date element.
func (d XMLDate) MarshalText() ([]byte, error) {
	return []byte(d.Time.Format("2006-01-02")), nil
}

// UnmarshalText parses a CCYY-MM-DD date.
func (d *XMLDate) UnmarshalText(data []byte) error {
	parsed, err := time.Parse("2006-01-02", string(data))
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

// MarshalJSON renders the date as a CCYY-MM-DD JSON string.
func (d XMLDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Time.Format("2006-01-02"))
}

// UnmarshalJSON parses a CCYY-MM-DD JSON string.
func (d *XMLDate) UnmarshalJSON(data []byte) error {
	var dateStr string
	if err := json.Unmarshal(data, &dateStr); err != nil {
		return err
	}
	parsed, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

func (d XMLDate) String() string {
	return d.Time.Format("2006-01-02")
}
