// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package api

import (
	"bytes"
	"encoding/xml"
)

// Example defines model for example.
type Example struct {
	Value *string `json:"value,omitempty" xml:"value"`
}

// Reusableresponse defines model for reusableresponse.
type Reusableresponse = Example

type RawMessage []byte

// MarshalJSON returns the raw bytes as JSON.
func (r RawMessage) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	return r, nil
}

// UnmarshalJSON sets the raw bytes from JSON input.
func (r *RawMessage) UnmarshalJSON(data []byte) error {
	*r = append((*r)[0:0], data...)
	return nil
}

// MarshalXML encodes the raw XML message into the encoder, re-wrapping
// it within the provided start element.
func (r RawMessage) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(r) == 0 {
		return nil
	}

	d := xml.NewDecoder(bytes.NewReader(r))
	// Skip the original start element from the stored raw XML
	_, err := d.Token()
	if err != nil {
		return err
	}

	// Write the caller-provided start element
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	// Copy all inner tokens until we reach the matching end element
	depth := 1
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
			if depth == 0 {
				return e.EncodeToken(start.End())
			}
		}
		if err := e.EncodeToken(xml.CopyToken(tok)); err != nil {
			return err
		}
	}
}

// UnmarshalXML captures a full XML element (including children) into raw bytes.
func (r *RawMessage) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	data, err := CaptureXMLElement(d, start)
	if err != nil {
		return err
	}
	*r = data
	return nil
}

// CaptureXMLElement reads an entire XML element from the decoder and returns it as bytes.
func CaptureXMLElement(d *xml.Decoder, start xml.StartElement) ([]byte, error) {
	buf := new(bytes.Buffer)
	encoder := xml.NewEncoder(buf)

	if err := encoder.EncodeToken(start); err != nil {
		return nil, err
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return nil, err
		}

		if err = encoder.EncodeToken(tok); err != nil {
			return nil, err
		}

		if end, ok := tok.(xml.EndElement); ok && end.Name == start.Name {
			encoder.Flush()
			break
		}
	}

	return buf.Bytes(), nil
}

// MultipleRequestAndResponseTypesTextBody defines parameters for MultipleRequestAndResponseTypes.
type MultipleRequestAndResponseTypesTextBody = string

// TextExampleTextBody defines parameters for TextExample.
type TextExampleTextBody = string

// HeadersExampleParams defines parameters for HeadersExample.
type HeadersExampleParams struct {
	Header1 string `json:"header1" xml:"header1"`
	Header2 *int   `json:"header2,omitempty" xml:"header2"`
}

// JSONExampleJSONRequestBody defines body for JSONExample for application/json ContentType.
type JSONExampleJSONRequestBody = Example

// MultipartExampleMultipartRequestBody defines body for MultipartExample for multipart/form-data ContentType.
type MultipartExampleMultipartRequestBody = Example

// MultipartRelatedExampleMultipartRequestBody defines body for MultipartRelatedExample for multipart/related ContentType.
type MultipartRelatedExampleMultipartRequestBody = Example

// MultipleRequestAndResponseTypesJSONRequestBody defines body for MultipleRequestAndResponseTypes for application/json ContentType.
type MultipleRequestAndResponseTypesJSONRequestBody = Example

// MultipleRequestAndResponseTypesFormdataRequestBody defines body for MultipleRequestAndResponseTypes for application/x-www-form-urlencoded ContentType.
type MultipleRequestAndResponseTypesFormdataRequestBody = Example

// MultipleRequestAndResponseTypesMultipartRequestBody defines body for MultipleRequestAndResponseTypes for multipart/form-data ContentType.
type MultipleRequestAndResponseTypesMultipartRequestBody = Example

// MultipleRequestAndResponseTypesTextRequestBody defines body for MultipleRequestAndResponseTypes for text/plain ContentType.
type MultipleRequestAndResponseTypesTextRequestBody = MultipleRequestAndResponseTypesTextBody

// ReusableResponsesJSONRequestBody defines body for ReusableResponses for application/json ContentType.
type ReusableResponsesJSONRequestBody = Example

// TextExampleTextRequestBody defines body for TextExample for text/plain ContentType.
type TextExampleTextRequestBody = TextExampleTextBody

// URLEncodedExampleFormdataRequestBody defines body for URLEncodedExample for application/x-www-form-urlencoded ContentType.
type URLEncodedExampleFormdataRequestBody = Example

// HeadersExampleJSONRequestBody defines body for HeadersExample for application/json ContentType.
type HeadersExampleJSONRequestBody = Example

// UnionExampleJSONRequestBody defines body for UnionExample for application/json ContentType.
type UnionExampleJSONRequestBody = Example
