// Package xomitzero provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package xomitzero

import (
	"bytes"
	"encoding/xml"
)

// Client defines model for Client.
type Client struct {
	Id   *float32 `json:"id,omitempty" xml:"id"`
	Name string   `json:"name" xml:"name"`
}

// ClientWithExtension defines model for ClientWithExtension.
type ClientWithExtension struct {
	Id   *float32 `json:"id,omitempty,omitzero" xml:"id"`
	Name string   `json:"name" xml:"name"`
}

// ContainerTypeWithOptional defines model for ContainerTypeWithOptional.
type ContainerTypeWithOptional struct {
	HasIsZero *FieldWithCustomIsZeroMethod `json:"has_is_zero,omitempty,omitzero" xml:"has_is_zero"`
}

// ContainerTypeWithRequired defines model for ContainerTypeWithRequired.
type ContainerTypeWithRequired struct {
	HasIsZero FieldWithCustomIsZeroMethod `json:"has_is_zero,omitzero" xml:"has_is_zero"`
}

// FieldWithCustomIsZeroMethod defines model for FieldWithCustomIsZeroMethod.
type FieldWithCustomIsZeroMethod struct {
	Id    *string  `json:"id,omitempty" xml:"id"`
	Value *float32 `json:"value,omitempty" xml:"value"`
}

// FieldWithOmitZeroOnRequiredField defines model for FieldWithOmitZeroOnRequiredField.
type FieldWithOmitZeroOnRequiredField struct {
	Id string `json:"id,omitzero" xml:"id"`
}

type RawMessage []byte

// MarshalJSON returns the raw bytes as JSON.
func (r RawMessage) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	return r, nil
}

// UnmarshalJSON sets the raw bytes from JSON input.
func (r *RawMessage) UnmarshalJSON(data []byte) error {
	*r = append((*r)[0:0], data...)
	return nil
}

// MarshalXML encodes the raw XML message into the encoder, re-wrapping
// it within the provided start element.
func (r RawMessage) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(r) == 0 {
		return nil
	}

	d := xml.NewDecoder(bytes.NewReader(r))
	// Skip the original start element from the stored raw XML
	_, err := d.Token()
	if err != nil {
		return err
	}

	// Write the caller-provided start element
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	// Copy all inner tokens until we reach the matching end element
	depth := 1
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
			if depth == 0 {
				return e.EncodeToken(start.End())
			}
		}
		if err := e.EncodeToken(xml.CopyToken(tok)); err != nil {
			return err
		}
	}
}

// UnmarshalXML captures a full XML element (including children) into raw bytes.
func (r *RawMessage) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	data, err := CaptureXMLElement(d, start)
	if err != nil {
		return err
	}
	*r = data
	return nil
}

// CaptureXMLElement reads an entire XML element from the decoder and returns it as bytes.
func CaptureXMLElement(d *xml.Decoder, start xml.StartElement) ([]byte, error) {
	buf := new(bytes.Buffer)
	encoder := xml.NewEncoder(buf)

	if err := encoder.EncodeToken(start); err != nil {
		return nil, err
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return nil, err
		}

		if err = encoder.EncodeToken(tok); err != nil {
			return nil, err
		}

		if end, ok := tok.(xml.EndElement); ok && end.Name == start.Name {
			encoder.Flush()
			break
		}
	}

	return buf.Bytes(), nil
}
